In [1]:
import torch

/home/sobhan/miniconda3/envs/ml-dl/lib/python3.9/site-packages/torch/cuda/__init__.py:83: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 9010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  ../c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0


In [31]:
from torch import nn

In [80]:
inp = torch.rand((1, 1,  8,8))

In [81]:
inp.shape

torch.Size([1, 1, 8, 8])

In [82]:
conv2d = nn.Sequential(
                        nn.Conv2d(in_channels=1, out_channels=1, kernel_size=(3,3), padding=1, padding_mode='circular' )
    )

In [83]:
conv2d(inp).shape

torch.Size([1, 1, 8, 8])

In [84]:
conv2d(inp)

tensor([[[[ 0.2013,  0.1961,  0.1287, -0.0040,  0.2438,  0.1158,  0.2117,
            0.2508],
          [ 0.1372, -0.0087,  0.1810,  0.2404,  0.2648,  0.0526,  0.0786,
            0.3093],
          [ 0.1120,  0.1049,  0.0068,  0.0114,  0.0915,  0.1665,  0.2386,
            0.0901],
          [ 0.2332,  0.1381,  0.1432,  0.1068,  0.1469,  0.3199,  0.0932,
            0.1930],
          [ 0.1462,  0.1788,  0.1657,  0.2518,  0.1377,  0.1315,  0.1465,
            0.0907],
          [ 0.1537,  0.1089,  0.2098,  0.0765, -0.0075,  0.1412, -0.0485,
            0.1074],
          [ 0.0219,  0.0590,  0.0538,  0.3766,  0.2427,  0.0006,  0.0771,
            0.0826],
          [ 0.1637,  0.3199,  0.0801,  0.1369,  0.3261,  0.1510,  0.1315,
            0.0364]]]], grad_fn=<ConvolutionBackward0>)

In [85]:
conv2d.state_dict()

OrderedDict([('0.weight',
              tensor([[[[-0.1011, -0.1651,  0.0065],
                        [ 0.2536,  0.0363, -0.1115],
                        [ 0.1152,  0.0192,  0.0655]]]])),
             ('0.bias', tensor([0.0836]))])

In [86]:
inp

tensor([[[[0.7402, 0.5755, 0.1095, 0.7621, 0.1777, 0.3660, 0.4312, 0.6223],
          [0.1792, 0.7044, 0.7901, 0.9427, 0.0970, 0.3180, 0.8317, 0.9875],
          [0.5367, 0.3452, 0.3888, 0.2949, 0.2794, 0.5913, 0.8805, 0.2058],
          [0.2393, 0.2682, 0.1931, 0.2357, 0.8824, 0.8266, 0.4304, 0.8500],
          [0.5346, 0.3881, 0.6919, 0.7648, 0.8529, 0.4778, 0.6609, 0.2324],
          [0.3576, 0.7220, 0.5316, 0.1218, 0.7513, 0.2780, 0.2902, 0.8430],
          [0.1665, 0.1890, 0.8938, 0.7173, 0.1739, 0.1647, 0.4117, 0.1519],
          [0.9934, 0.4527, 0.8370, 0.9411, 0.2174, 0.1711, 0.0682, 0.0498]]]])

In [93]:
a = torch.tensor(
[[0.1665, 0.1890, 0.8938], 
 [0.9934, 0.4527, 0.8370], 
 [0.7402, 0.5755, 0.1095]]
)

In [94]:
w = torch.tensor(
    [[-0.1011, -0.1651,  0.0065],
                        [ 0.2536,  0.0363, -0.1115],
                        [ 0.1152,  0.0192,  0.0655]]
)

In [95]:
torch.sum(a*w)+0.0836

tensor(0.3199)