In [2]:
import torch

In [3]:
from torch import nn

In [31]:
inp = torch.rand((1, 1,  80,80))

In [32]:
inp.shape

torch.Size([1, 1, 80, 80])

In [44]:
conv2d = nn.Sequential(
                        nn.Conv2d(in_channels=1, out_channels=1, 
                                  dilation=2, 
                                  kernel_size=(1,1), 
                                  padding=0, 
                                  padding_mode='circular' )
    )

In [45]:
conv2d(inp).shape

torch.Size([1, 1, 80, 80])

In [10]:
conv2d(inp)

tensor([[[[-0.2409, -0.1985, -0.2849, -0.3101, -0.1943, -0.2154, -0.1756,
           -0.3998],
          [-0.1949, -0.2045, -0.1917, -0.2363, -0.2956, -0.0244, -0.2859,
           -0.4407],
          [-0.1327, -0.2820, -0.0847, -0.3180, -0.1149,  0.0530, -0.4420,
           -0.2977],
          [-0.3710, -0.3298, -0.1268, -0.4764, -0.1392, -0.0875, -0.6154,
           -0.3324],
          [-0.1424, -0.1553, -0.0971, -0.0505,  0.1582, -0.3146, -0.3889,
            0.0186],
          [-0.3148, -0.2503, -0.2263, -0.1499, -0.0861, -0.3181, -0.1216,
           -0.1283],
          [-0.3469,  0.0033, -0.0277, -0.2676, -0.4867, -0.3218, -0.2261,
           -0.0488],
          [-0.1188, -0.4074, -0.1821, -0.0679, -0.2864, -0.3824, -0.2885,
            0.0307]]]], grad_fn=<ConvolutionBackward0>)

In [11]:
conv2d.state_dict()

OrderedDict([('0.weight',
              tensor([[[[-0.1445, -0.2179,  0.1840],
                        [-0.2276, -0.2232,  0.0671],
                        [-0.0224,  0.2343,  0.0852]]]])),
             ('0.bias', tensor([-0.0826]))])

In [12]:
inp

tensor([[[[0.6067, 0.2387, 0.4413, 0.9285, 0.3685, 0.4486, 0.8073, 0.8457],
          [0.2939, 0.5545, 0.6257, 0.3026, 0.4153, 0.6262, 0.9853, 0.3456],
          [0.7584, 0.4015, 0.0971, 0.9699, 0.0205, 0.6516, 0.9001, 0.2926],
          [0.7012, 0.2191, 0.8090, 0.2604, 0.4581, 0.7856, 0.7845, 0.5365],
          [0.3655, 0.3079, 0.2622, 0.1760, 0.0478, 0.8183, 0.1283, 0.1174],
          [0.9791, 0.0372, 0.8825, 0.6632, 0.9589, 0.2325, 0.1535, 0.6547],
          [0.6112, 0.3572, 0.0700, 0.9180, 0.8368, 0.6555, 0.6007, 0.0340],
          [0.3501, 0.9913, 0.7388, 0.1774, 0.5910, 0.8827, 0.2909, 0.4205]]]])

In [93]:
a = torch.tensor(
[[0.1665, 0.1890, 0.8938], 
 [0.9934, 0.4527, 0.8370], 
 [0.7402, 0.5755, 0.1095]]
)

In [94]:
w = torch.tensor(
    [[-0.1011, -0.1651,  0.0065],
                        [ 0.2536,  0.0363, -0.1115],
                        [ 0.1152,  0.0192,  0.0655]]
)

In [95]:
torch.sum(a*w)+0.0836

tensor(0.3199)