In [1]:
import numpy as np

In [2]:
from sklearn.linear_model import LinearRegression

# Linear Regression

In [6]:
X = np.random.randint(low=1, high=5, size=(6,3))
Y = 2*X[:,0] + 1.2 * X[:, 1]-2.1

In [7]:
reg = LinearRegression()

In [8]:
reg.fit(X, Y)

LinearRegression()

In [6]:
reg.score(X, Y)

1.0

In [7]:
reg.coef_

array([ 2.00000000e+00,  1.20000000e+00, -1.11022302e-16])

In [8]:
reg.intercept_

-2.1000000000000023

In [9]:
reg.predict([[8,2,2]])

array([16.3])

In [10]:
reg.rank_

3

In [11]:
reg.singular_

array([2.30569855, 1.58545847, 0.58029504])

# Ridge

In [12]:
from sklearn.linear_model import Ridge

In [13]:
reg = Ridge(alpha=.5)

In [14]:
reg.fit(X, Y)

Ridge(alpha=0.5)

In [15]:
reg.score(X, Y)

0.9881737385321102

In [16]:
reg.coef_

array([1.8, 1. , 0.1])

In [17]:
reg.intercept_

-1.1500000000000012

# RidgeCV (Ridge cross-validation)

In [18]:
from sklearn.linear_model import RidgeCV

In [19]:
# no one is sure about which alpha is the best
# for the case of Ridge classifier. But here, 
# you can specify a range for alpha selection and
# it will do it based on the best alpha it can find

reg = RidgeCV(alphas=(0.0004,0.5,0.75 ,1.0, 2,100)) 

In [20]:
X = np.random.randint(low=1, high=6, size=(100,150)) 
Y = X.sum(axis=1) # + np.random.random(((100,1)))

In [21]:
reg.fit(X,Y)

RidgeCV(alphas=(0.0004, 0.5, 0.75, 1.0, 2, 100))

In [22]:
reg.score(X, Y)

0.9999999999977189

In [23]:
# which alpha was the best?
reg.alpha_

0.0004

In [24]:
# so the best practice is:
reg = RidgeCV(alphas=np.linspace(0.002, 10, 130))

In [25]:
reg.fit(X,Y)

RidgeCV(alphas=array([2.00000000e-03, 7.95038760e-02, 1.57007752e-01, 2.34511628e-01,
       3.12015504e-01, 3.89519380e-01, 4.67023256e-01, 5.44527132e-01,
       6.22031008e-01, 6.99534884e-01, 7.77038760e-01, 8.54542636e-01,
       9.32046512e-01, 1.00955039e+00, 1.08705426e+00, 1.16455814e+00,
       1.24206202e+00, 1.31956589e+00, 1.39706977e+00, 1.47457364e+00,
       1.55207752e+00, 1.62958140e+0...
       8.06240310e+00, 8.13990698e+00, 8.21741085e+00, 8.29491473e+00,
       8.37241860e+00, 8.44992248e+00, 8.52742636e+00, 8.60493023e+00,
       8.68243411e+00, 8.75993798e+00, 8.83744186e+00, 8.91494574e+00,
       8.99244961e+00, 9.06995349e+00, 9.14745736e+00, 9.22496124e+00,
       9.30246512e+00, 9.37996899e+00, 9.45747287e+00, 9.53497674e+00,
       9.61248062e+00, 9.68998450e+00, 9.76748837e+00, 9.84499225e+00,
       9.92249612e+00, 1.00000000e+01]))

In [26]:
reg.alpha_

0.002

In [27]:
reg.intercept_


156.8446926405888

In [28]:
# reg.coef_

In [29]:
reg.score(X, Y)

0.9999999999429764

In [30]:
# don't know why it is negative
reg.best_score_

-61.77915428751257

In [31]:
reg.get_params()

{'alpha_per_target': False,
 'alphas': array([2.00000000e-03, 7.95038760e-02, 1.57007752e-01, 2.34511628e-01,
        3.12015504e-01, 3.89519380e-01, 4.67023256e-01, 5.44527132e-01,
        6.22031008e-01, 6.99534884e-01, 7.77038760e-01, 8.54542636e-01,
        9.32046512e-01, 1.00955039e+00, 1.08705426e+00, 1.16455814e+00,
        1.24206202e+00, 1.31956589e+00, 1.39706977e+00, 1.47457364e+00,
        1.55207752e+00, 1.62958140e+00, 1.70708527e+00, 1.78458915e+00,
        1.86209302e+00, 1.93959690e+00, 2.01710078e+00, 2.09460465e+00,
        2.17210853e+00, 2.24961240e+00, 2.32711628e+00, 2.40462016e+00,
        2.48212403e+00, 2.55962791e+00, 2.63713178e+00, 2.71463566e+00,
        2.79213953e+00, 2.86964341e+00, 2.94714729e+00, 3.02465116e+00,
        3.10215504e+00, 3.17965891e+00, 3.25716279e+00, 3.33466667e+00,
        3.41217054e+00, 3.48967442e+00, 3.56717829e+00, 3.64468217e+00,
        3.72218605e+00, 3.79968992e+00, 3.87719380e+00, 3.95469767e+00,
        4.03220155e+00, 4.

In [32]:
re = Ridge(alpha=0.0978511627906976)

In [33]:
re.fit(X, Y)

Ridge(alpha=0.0978511627906976)

In [34]:
re.score(X,Y)

0.9999998639471317

# Lasso

In [35]:
from sklearn.linear_model import Lasso

In [36]:
reg = Lasso() # equal to Lasso(alpha=0)

In [37]:

reg.fit(X, Y)

Lasso()

In [38]:
reg.score(X, Y)

0.9220067139516535

# LassoCV

In [39]:
from sklearn.linear_model import LassoCV

In [40]:
reg = LassoCV(alphas=np.linspace(1,10,3000))

In [41]:
reg.fit(X, Y)

LassoCV(alphas=array([ 1.      ,  1.003001,  1.006002, ...,  9.993998,  9.996999,
       10.      ]))

In [42]:
reg.alpha_

1.0